name: Anhanguera

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  IMAGEM_DOCKERHUB: ${{ secrets.DOCKERHUB_USERNAME }}/sitestecnologia
  NOME_WEBAPP: groffeanhanguera
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build de imagem
      run: |
        cd ./SiteCanaisTecnologia
        ls
        docker build . --file Dockerfile --tag ${{ env.IMAGEM_DOCKERHUB }}:latest
        docker tag ${{ env.IMAGEM_DOCKERHUB }}:latest ${{ env.IMAGEM_DOCKERHUB }}:$GITHUB_RUN_NUMBER

    - name: Login no Docker Hub
      uses: docker/login-action@v1.10.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Geração de tag com número do Build e Push no Docker Hub
      run: |
        docker push --all-tags ${{ env.IMAGEM_DOCKERHUB }}
